from django.db import models

class Database(models.Model):
    mother_name = models.TextField(blank=True)
    mother_mark = models.TextField(blank=True)
    mother_type = models.TextField(blank=True)
    mother_made = models.TextField(blank=True)
    mother_doc = models.TextField(blank=True)
    mother_status = models.TextField(blank=True)
    red_type = models.TextField(blank=True)
    red_mark = models.TextField(blank=True)
    red_designation = models.TextField(blank=True)
    red_nominal = models.TextField(blank=True)
    red_efficiency = models.TextField(blank=True)
    red_made = models.TextField(blank=True)
    red_doc = models.TextField(blank=True)
    red_status = models.TextField(blank=True)
    orange_type = models.TextField(blank=True)
    orange_mark = models.TextField(blank=True)
    orange_designation = models.TextField(blank=True)
    orange_nominal = models.TextField(blank=True)
    orange_efficiency = models.TextField(blank=True)
    orange_made = models.TextField(blank=True)
    orange_doc = models.TextField(blank=True)
    orange_status = models.TextField(blank=True)
    yellow_type = models.TextField(blank=True)
    yellow_mark = models.TextField(blank=True)
    yellow_designation = models.TextField(blank=True)
    yellow_nominal = models.TextField(blank=True)
    yellow_efficiency = models.TextField(blank=True)
    yellow_made = models.TextField(blank=True)
    yellow_doc = models.TextField(blank=True)
    yellow_status = models.TextField(blank=True)
    green_type = models.TextField(blank=True)
    green_mark = models.TextField(blank=True)
    green_designation = models.TextField(blank=True)
    green_nominal = models.TextField(blank=True)
    green_efficiency = models.TextField(blank=True)
    green_made = models.TextField(blank=True)
    green_doc = models.TextField(blank=True)
    green_status = models.TextField(blank=True)
    blue_type = models.TextField(blank=True)
    blue_mark = models.TextField(blank=True)
    blue_designation = models.TextField(blank=True)
    blue_nominal = models.TextField(blank=True)
    blue_efficiency = models.TextField(blank=True)
    blue_made = models.TextField(blank=True)
    blue_doc = models.TextField(blank=True)
    blue_status = models.TextField(blank=True)
    indigo_type = models.TextField(blank=True)
    indigo_mark = models.TextField(blank=True)
    indigo_designation = models.TextField(blank=True)
    indigo_nominal = models.TextField(blank=True)
    indigo_efficiency = models.TextField(blank=True)
    indigo_made = models.TextField(blank=True)
    indigo_doc = models.TextField(blank=True)
    indigo_status = models.TextField(blank=True)
    violet_type = models.TextField(blank=True)
    violet_mark = models.TextField(blank=True)
    violet_designation = models.TextField(blank=True)
    violet_nominal = models.TextField(blank=True)
    violet_efficiency = models.TextField(blank=True)
    violet_made = models.TextField(blank=True)
    violet_doc = models.TextField(blank=True)
    violet_status = models.TextField(blank=True)
    coord = models.TextField(blank=True)
    photo = models.ImageField(upload_to='photos/%Y/%m/%d/')






